### ISSUE TITLE
Three-phase wait-free readout

### ISSUE THREAD

**Issue by spaulaus** [pixie16/paass#10]
Implement three-phase wait-free readout

**Comment by ksmith0** [comment]
Can we get some clarification on the meaning of this?

**Comment by spaulaus** [comment]
This is something that was in the TODO list inherited from @damiller. Maybe he can clarify for us?

**Comment by spaulaus** [comment]
An update from David about this issue: 

> Read 2-words, this will give you the size of the first event
> Read all but the last two words in the buffer or wait until they are available
> Read last two words.
> 
> This should pretty much avoid the partial event waiting.
> The real best thing to do would to be properly implement a double buffer that passes the events accordingly to the backend when they are available

>

**Comment by ksmith0** [comment]
This was one of the major changes in poll2. We currently read out the number of words available parse the buffer and separate the partial event, then without waiting continue poll the rest of the modules. The next time the module with the partial event is polled the partial event is pretended to the buffer that's read out completing the buffer.

**Comment by spaulaus** [comment]
Ah, great! Then this is already implemented. I will close the issue.
