### ISSUE TITLE
Running utkscan with no output specified creates hard to delete files.

### ISSUE THREAD

**Issue by ksmith0** [pixie16/paass#120]
The files `\002.dat` and `\002.root` are created. These are difficult to delete as they appear in a listing as `?.dat` and `?.root`

**Comment by spaulaus** [comment]
Neat. I will look into it.

**Comment by ksmith0** [comment]
Any progress on this? pc0084188 is starting to collect these all over.

**Comment by spaulaus** [comment]
Nope
