### ISSUE TITLE
Static Int Order Fiasco

### ISSUE THREAD

**Issue by spaulaus** [pixie16/paass#13]
The scan software suffers from [Static Initialization Order Fiasco](https://isocpp.org/wiki/faq/ctors#static-init-order) with respect to the Globals and Plots class. The classes are initialized before the main function executes. This is the root cause for Issue #12. 

It is not clear if the solution proposed in the above link will solve our problems.

**Comment by spaulaus** [comment]
This happens most commonly with statics defined at the top of the cpp files that use the Globals class, in addition it occurs in the namespaces for the histograms. It is unclear at this point how many times this occurs, but these should be fixed.

**Comment by ksmith0** [comment]
Was this a bug with PixieSuite?

**Comment by spaulaus** [comment]
This particular issue was directed more at utkscan. It came from static variables calling the Globals singleton globally in some cpp files. I have not confirmed that this occurs for any of the DAQ software, but it would be useful to check.
