### ISSUE TITLE
Acquisition fails after changing SlotID

### ISSUE THREAD

**Issue by spaulaus** [pixie16/paass#138]
## Testing Procedure
1. Setup acquisition to verify that we are taking data properly. 
2. Used montior to verify that the data rates were correct. 
3. Used mca to verify that the spectra were appropriate. 
1. Change SlotID : `pmwrite 0 SlotID 5`
2. `startvme` -> Now we have received the error message: 
https://drive.google.com/file/d/0B_XQp_kYuMwQZGo2S2drc0pLYkU/view?usp=sharing
7. Change back to SlotID 2. 
8. `startvme` -> This still produces the same errors as before. 
https://drive.google.com/file/d/0B_XQp_kYuMwQZ2xPMmFta0FacEk/view?usp=sharing
8. Restart poll 
9. Enable traces on Module 0 Channel 0. 
10. Change SlotID to 5
11. `startvme` -> https://drive.google.com/file/d/0B_XQp_kYuMwQSlQ3WmFkX1BVNGs/view?usp=sharing
12. Change SlotID to 2
13. `startvme` -> The system runs as expected with no issues. 

# Summary 
It seems to me that there is something deeper going on when we are modifying the SlotID. Could this be something with the API? It would also seem that poll2 is able to handle recovery after reading traces much better than when it just has the four header words. I think that this needs to be investigated a little more.

**Comment by ksmith0** [comment]
We do not change the SlotID in any typical setup, so I'm closing this as wontfix until there is a reason for working on it.
