### ISSUE TITLE
As a user I would like to use the colon ranges for module commands.

### ISSUE THREAD

**Issue by spaulaus** [pixie16/paass#139]
The colon ranges ( `pwrite 0:4 4:13 TRACE_LENGTH 200` ) should be implemented with the module specific parameters as well. 

1. Colon range does not work with adjust_offsets, pmread/write, toggle, get_traces
2. csr_test does not accept hex input.

**Comment by ksmith0** [comment]
Added functionality to the follwing commands int he corresponding commit:
* pmread / pmwrite: a7043a63d172b7551fb6c6bf3d2c8d8cf1ec294e
* adjust_offsets: b71f43a41792ee72f8a87da29f9fca37037ca7da
* toggle: dbe629aa144d2f37585b9607af8d7c4495b47471
* csr_test: ff14dd232ec1003faed2e88bf75000aeab67da22

`get_traces` is currently designed to only take a single channel as an argument. I would suggest we open a new issue for this as it is not as simple as the work done for the other commands.
