### ISSUE TITLE
Sort auto-configured pixie.cfg file.

### ISSUE THREAD

**Issue by ksmith0** [pixie16/paass#146]
This idea came up during merge request #128:

>4. Sorting pixie.cfg by revision (?) This may not be critical but would be nice.

This is more work as the ModuleType is determined after entering a directory and the output is written out while parsing the files inside that directory. To do as you ask one would need to store the output into a string (can you store multiple lines in a cmake string?). This string is somehow associated with the tag then you would need to sort the tags (not sure this is possible in cmake) and output the associated string.

In addition, one would want to sort by revision, then adc resolution, then sample speed.

**Comment by spaulaus** [comment]
Do we really even need this? It would be nice, but as long as things are clearly documented then it shouldn't matter.

**Comment by ksmith0** [comment]
It was your suggestion, but it is very difficult. I agree with you that things are clear enough. Closing as wontfix.

**Comment by spaulaus** [comment]
I remember suggesting it, but have rethought it.
