### ISSUE TITLE
Read Firmware Revision and Frequency from the Config.xml

### ISSUE THREAD

**Issue by tking53** [pixie16/paass#157]
The new flags for utkscan are not immediately useful for an end user, since once data is taken these flags won't change. So I propose that they be moved to the Config.xml while possibly retaining the flags as overrides to the Config.xml; since they are useful for testing new firmwares/modules.

**Comment by spaulaus** [comment]
The flags are useful, since some of the programs do not have configuration files. Also, remember we have things like scope that can attach to a shared memory stream. It would need to know this information to unpack the data properly.

**Comment by spaulaus** [comment]
This is turning out to be much more complicated than initially thought. The initialization of the configuration file comes after these values are set in the Unpacker. At the moment, there's no easy way to implement this without disentangling the circular dependency of the ScanInterface and Unpacker (Issue #29). 

This would put a call to the utkscan Globals class in ScanInterface, which is not something we want to do.

**Comment by spaulaus** [comment]
I'm removing this from the RC since it's unnecessary at the moment, and only adds complexity to a problem that is larger than people realize.
