### ISSUE TITLE
scope Segfaults when scanning 

### ISSUE THREAD

**Issue by tking53** [pixie16/paass#160]
here is the gdb output
![scope-issue](https://cloud.githubusercontent.com/assets/18449805/21722719/d5ba8a64-d3fb-11e6-9cdb-5b2f315ff0e2.png)

**Comment by spaulaus** [comment]
@tking53 Was this ever addressed?

**Comment by tking53** [comment]
Nope not yet.

**Comment by spaulaus** [comment]
It's fixed now.
