### ISSUE TITLE
Trace ComputeBaseline minimum bins is too restrictive

### ISSUE THREAD

**Issue by tking53** [pixie16/paass#161]
The hardcoded value of 30 bins necessary for the Baseline calculation is to restrictive as some of the older data does not have that much available. It would be nice to have this in the Trace node in the Config.xml.  

" WaveformAnalyzer::Analyze - TraceFunctions::ComputeBaseline - The range specified is smaller than the minumum necessary range. "

**Comment by spaulaus** [comment]
This was fixed in pull request #162. The value was changed to 10 bins from 30 bins.
