### ISSUE TITLE
TreeCorrelator getting bad place

### ISSUE THREAD

**Issue by spaulaus** [pixie16/paass#168]
The TreeCorrelator is attempting to get a bad place in the DetectorDriver. We are checking for `__-1` but getting `__4294967295`. This is a signed vs unsigned int issue, that I am currently having trouble tracking down. The error is occurring at line 324 in detector driver.

**Comment by ksmith0** [comment]
From dev branch [ paass/Scan/utkscan/core/source/DetectorDriver.cpp](https://github.com/pixie16/paass/blob/dev/Scan/utkscan/core/source/DetectorDriver.cpp)
```c++
string place = (*it)->GetChanID().GetPlaceName();
if (place == "__-1")
  continue;
```
Where `(*it)` is a `ChanEvent*`.

`ChanEvent::GetChanID ()` returns an `Identifier&`

`Identifier::GetPlaceName()` calls `Identifier::GetLocation()` as follows:
```c++
/** \return The name of the place associated with the channel */
std::string GetPlaceName() const {
    std::stringstream ss;
    ss << GetType() << "_" << GetSubtype() << "_" << GetLocation();
    return ss.str();
}
```

`Identifer::GetLcoation()` returns `Identifier::location` which is set to -1 in `Identifier::Zero()`

I suspect the following, but have not yet made the connection:
`Identifier::GetTag()` returns an `int` equal to `std::numeric_limits<int>::max()` if the tag is not found. This value is equal to `INT_MAX` which is not -1. You are reporting that you are getting `U LONG_MAX` which should be the max value for an `unsigned long int`. http://www.cplusplus.com/reference/climits/

**Comment by spaulaus** [comment]
Nailed it. Thanks @ksmith0

**Comment by ksmith0** [comment]
I still don't see how your commit resolved the issue. You changed the default value from -1 to 9999 (did not update the if statement in DetectorDriver) and removed the Getter calls in GetPlaceName, which should have been returning the values as you changed them to. Should this behavior not just be the same?

**Comment by spaulaus** [comment]
You are correct. I forgot to stage the DetectorDriver.

**Comment by ksmith0** [comment]
I understand now. The `location` was an `unsigned` thus setting it to -1 causes it to set to the maximum value. Changing to 9999 ensures a value that can be checked against. This does not permit a user to a 10,000 channel system and it may have been better / easier to simply change the if statement to check against the largest possible value of `unsigned int`. The issue was resolved with your commit and has been merged.

**Comment by spaulaus** [comment]
10,000 channels? Unlikely for the near future. That said, there are larger issues with the tree correlator that need addressed.
