### ISSUE TITLE
New or Alternate flag for Frequency

### ISSUE THREAD

**Issue by tking53** [pixie16/paass#179]
Changing the `--frequency` flag to something shorter say `-q` or `--freq`, would help from an everyday usability standpoint.

**Comment by spaulaus** [comment]
`-q` is already taken. `--freq` is not as clear in my opinion. In general, people are going to type this once and then use up arrows or bash scripts.

**Comment by tking53** [comment]
how about --hz? and the bash scripts will require #178 to be really usable. We are just looking for something shorter since the `./utkscan ...` has gotten really long (especially if you have paths to configs / input files)

**Comment by spaulaus** [comment]
`--hz` is even more esoteric. `--MSps` might be a little clearer, but doesn't really help. Bash scripts do not need #178 to be finished in order to be useful. You can build multiple ROOT files and chain them together fairly trivially.

**Comment by ksmith0** [comment]
@spaulaus And what about damm histograms?

**Comment by spaulaus** [comment]
DAMM histograms can also be added together using a program called hisadd.

I do not know why the histograms are zeroed when you start a new scan that would be a question for @cthornsb

**Comment by ksmith0** [comment]
I propose we move the discussion of #178 to it correct location. I will add your quote.

**Comment by ksmith0** [comment]
Closing as its labelled wontfix.
