### ISSUE TITLE
No clear location to find firmware options

### ISSUE THREAD

**Issue by ksmith0** [pixie16/paass#183]
Where can one find the information about the firmware choices? It does not seem to be in the wiki (I guess it would be here: https://github.com/pixie16/paass/wiki/Pixie-Firmware-Information) and the code does not offer up the options as explained below.

If one runs scope with a firmware option the following message is displayed:
```
 0
terminate called after throwing an instance of 'std::invalid_argument'
  what():  XiaListModeDataMask::CovnertStringToFirmware : Unrecognized firmware option - 

Aborted (core dumped)
```

It would be useful if this message explained the options. In addition the help line does not provide much help:
```
   --firmware (-f) <firmware>           - Sets the firmware revision for decoding the data
```

and finally running `scope --firmware` with no option does not provide much useful information either:
```
$ scope --firmware
scope: option '--firmware' requires an argument
```

**Comment by spaulaus** [comment]
Ah, the valid choices are in the documentation on the Slack channel. You can look in `Resources/include/HelperEnumerations.hpp` for more information. This information should be added to the wiki. 

I'm working on decoding the older data formats, which includes the change we discussed that checks the number against a range and chooses the right masks accordingly.

**Comment by spaulaus** [comment]
Documentation is here
https://github.com/pixie16/paass/wiki/Pixie-Firmware-Information
