### ISSUE TITLE
Scope does not require frequency, but crashes upon running.

### ISSUE THREAD

**Issue by ksmith0** [pixie16/paass#184]
When scope is evoked as 
```
scope -f R34688 -i /data/HAGRiD/run_001.ldf
```
It immediately exits with the following message:
```
Scope $ terminate called after throwing an instance of 'std::invalid_argument'
[READ] 1302 words (0%), GOOD = 1, LOST = 0                                      what():  XiaListModeDataMask::GetCfdFractionalTimeMask : Could not obtain a mask for firmware code 4 and frequency 0. Check your settings.
                                                                    Aborted (core dumped)
```

I believe the proper treatment should be that scope complains about the frequency not being defined and not start.

**Comment by spaulaus** [comment]
Probably true.

**Comment by spaulaus** [comment]
Scope actually does require the frequency, since the x-axis is presented in ns and not bins. It also needs the frequency to ensure that the data are decoded properly.

**Comment by ksmith0** [comment]
I should clarify that when running scope if the frequency is omitted it is not clear that it is required as it starts running. It is needed to correctly unpack and so forth.

**Comment by spaulaus** [comment]
This should be a pretty simple fix, and will help the other programs as well (utkscan, skeleton, etc).

**Comment by ksmith0** [comment]
This is also true for utkscan as I just discovered with @alourei. The command was
```
utkscan -c example.xml --firmware R30981
```
and the following error message was received:
```
utkscan $ run
utkscan $ terminate called after throwing an instance of 'std::invalid_argument'
[IDLE] Waiting for Unpacker...                                                    what():  XiaListModeDataMask::GetCfdFractionalTimeMask : Could not obtain a mask for firmware code 3 and frequency 0. Check your settings.
                                                           Aborted (core dumped)

```

**Comment by spaulaus** [comment]
Yes, I know, see my comment above that.....

**Comment by ksmith0** [comment]
Sorry I can't keep up with you.

**Comment by spaulaus** [comment]
You won't have to much longer!

**Comment by spaulaus** [comment]
I have created a pull request with a patch for this issue.
