### ISSUE TITLE
pulser.xml does not work with master utkscan

### ISSUE THREAD

**Issue by ksmith0** [pixie16/paass#185]
The file `share/utkscan/cfgs/pulser.xml` does not run with the master version of utkscan. The error message is:
```
   * Loading PulserProcessor                                     
                                                                  [FAIL]
Exception caught at DetectorDriver::DetectorDriver
	DetectorDriver: unknown processor typePulserProcessor
```

I believe the `PulserProcessor` has been removed and this file was not updated / removed.

**Comment by spaulaus** [comment]
That is correct. I am going to label this as a wontfix and close, since this same complaint could be applied to 90% of the configurations.

**Comment by ksmith0** [comment]
Can we then remove these config files? They confuse those who are not intimately familiar with the history of the scan code.

**Comment by spaulaus** [comment]
No, *should* be updated, but this is a rather massive undertaking. Especially since the format of these files is getting ready to change. Removing that one file means we have to remove all the others on the same argument.

**Comment by spaulaus** [comment]
I would suggest that the example.xml be updated, and make sure that all users use that as a base.
