### ISSUE TITLE
TraceFunctions::ComputeBaseline error message has typo. 

### ISSUE THREAD

**Issue by sztaylor89** [pixie16/paass#186]
when trying to run utkscan I get the following error message with a typo for minimum(it gives minumum):

```
WaveformAnalyzer::Analyze - TraceFunctions::ComputeBaseline - The range specified is smaller than the minumum necessary range.
```

**Comment by spaulaus** [comment]
@sztaylor89 Can you explain a little more. Also, please try to make your titles more specific.

**Comment by sztaylor89** [comment]
"minimum" is spelled wrong.
