### ISSUE TITLE
utkscan freezes with a modified example.xml

### ISSUE THREAD

**Issue by ksmith0** [pixie16/paass#187]
Working with @alourei when running utkscan as follows:
```
utkscan -c example.xml --firmware 30981 --frequency 250 -i run_002.ldf
```
The scan code seems to launch with no errors, but then simply sits with 200% CPU usage with the following message:
```
utkscan $
[IDLE] Waiting for Unpacker...
```
The xml file is the following:
[example.xml.txt](https://github.com/pixie16/paass/files/724215/example.xml.txt)

The run file is simply some pulser data into M0C0. A 5.4MB ldf can be provided.

**Comment by spaulaus** [comment]
Exciting, this is why I mentioned in #185 that the example.xml needed to be updated. Also, the template processors are there only for example purposes and should not be used when scanning data.

**Comment by ksmith0** [comment]
What do you suggest as a basic processor then to scan data?

**Comment by spaulaus** [comment]
Probably the TwoChannelTimingProcessor? that's about as basic as it gets.

**Comment by spaulaus** [comment]
If you do not need anything other than raw histograms (energies, rates, etc). you don't have to use any processor at all.

**Comment by spaulaus** [comment]
I've investigated this a bit, and I think this is due to the TemplateExperimentProcessor requesting information from the TreeCorrelator that don't exist. I cannot replicate the behavior that you observed. I will update the TemplateExperimentProcessors to try to fix this issue.

**Comment by spaulaus** [comment]
This is resolved on the dev branch. The example.xml file is invalid. However, the program now has proper error handling for empty TreeCorrelator nodes and will exit cleanly.
