### ISSUE TITLE
Clean up of XiaData, ChannelData, ChanEvent Classes

### ISSUE THREAD

**Issue by spaulaus** [pixie16/paass#2]
There is currently a mess of classes related to storage of the data from the pixie module (XiaData) and data that is processed after the fact (ChannelData/ChanEvent). These classes will need to be cleaned up and organized a little better so that we can actually use them in a coherent way.

**Comment by ksmith0** [comment]
This was worked on recently in Decoding Update #156.

**Comment by spaulaus** [comment]
Still not complete, but moving in the right direction.
