### ISSUE TITLE
poll2 in dev no longer acquires data

### ISSUE THREAD

**Issue by ksmith0** [pixie16/paass#204]
After commit 4eabf6ab659a5f8422a5f60c13f619d617915bf5 poll2 no longer acquires data from the pixie16 cards. The system appears to boot and `pread` / `pwrite` commands work as expected, while `startacq` and run never acquire any data, the monitor says zero after a hup and the status bar at the bottom says 0B/s. Rolling back to commit 62170fd490eeb093b319d021da3b854a8cc85867 restores functionality.

**Comment by ksmith0** [comment]
The latest commit in dev c8147ea8c500a75e4d04ffa9e0a609b92ef58ba4 acquires as expected. I assume that the directory structure rearrangement #202 resolved the issue in commit 7cc078a92f4e78d776.

**Comment by spaulaus** [comment]
I'm confused. Is there an issue or is there not an issue here?

**Comment by ksmith0** [comment]
There was an issue, but it was resolved I assume it was due to the cmake resturcturing.

**Comment by spaulaus** [comment]
That would be my guess, how did it appear and disappear? You should have gotten that whole line of commits at the same time.

**Comment by ksmith0** [comment]
We pulled before the restructure, but after the first cmake change. At commit 4eabf6a.

**Comment by spaulaus** [comment]
I get you now. Well, I'm glad I was able to properly restructure the repository.
