### ISSUE TITLE
PulserProcessor

### ISSUE THREAD

**Issue by spaulaus** [pixie16/paass#21]
The PulserProcessor is much closer to an experiment specific processor than it is anything else. This processor needs moved to the experiment specific setups.

**Comment by ksmith0** [comment]
What is the status of this? @wapmanzoo tried to add PulserProcessor to his config file and utkscan responded that it was invalid. We tried to find the file, but it seems to no longer exist?

**Comment by spaulaus** [comment]
Correct, the PulserProcessor has been removed and turned into the TwoChanTimingProcessor. The PulserProcessor did not do anything special with the pulser data type and was really a specific implementation of an experimental setup.

**Comment by ksmith0** [comment]
The config,xml should be updated to remove this as a valid choice.

**Comment by ksmith0** [comment]
Never mind, I see it was removed already. I'm  not sure where @wapmanzoo's config file came from.

The scan share items should be moved to Scan/utkscan

**Comment by spaulaus** [comment]
Yes, that is a common problem. In addition, not all of the configs for the scan get updated (simply too many to change if they are not going to be actively used).
