### ISSUE TITLE
Set Maximum LDF size to 2 GB to ensure backwards compatability

### ISSUE THREAD

**Issue by spaulaus** [pixie16/paass#217]
For LDFs we should set the maximum file size to 2GB so that we are always compatible with the HRIBF libraries.

**Comment by ksmith0** [comment]
I'm not sure this is a bug, but it was resolved in 3af995 and merged in #220 .

**Comment by spaulaus** [comment]
I consider it a bug because it produces LDF files that cannot be read with standard software.
