### ISSUE TITLE
XiaData::GetBaseline() needs documentation clarification

### ISSUE THREAD

**Issue by tking53** [pixie16/paass#230]
There is no indication in the code that XiaData::GetBaseline() requires options enabled on the modules and that we should (in general) use the HighResTimingData::GetAvgBaseline() which is calculated in the analyzers.

**Comment by spaulaus** [comment]
Users should not "in general" use one or the other. They should use the method that is appropriate to their specific needs.

**Comment by tking53** [comment]
Resolved by #231
