### ISSUE TITLE
Update the rootScanner so that it works with revisions to Unpacker and ScanInterface

### ISSUE THREAD

**Issue by spaulaus** [pixie16/paass#233]
# Description 
The rootScanner program is a useful for converting raw data files (ldf, pld) into a ROOT tree. The program's development has stalled due to conflicts with the Unpacker and ScanInterface. We should restart development since this program is useful for users that do not need complex data analysis. We should also consider changing the name as it's not clear from the name exactly what this program does.

This program is currently being developed on the `rootScanner` branch. 

# Work to be Done
1. Update the rootScanner so that it uses the latest versions of the Unpacker and ScanInterface. 
2. Confirm that the program works as expected without any histogramming functionality. 
3. Come up with a better name. 

# Acceptance Criteria
1. The program compiles without issues
2. The  program produces a root file containing a root tree. 
3. The root tree is populated with the raw information from the events in the data file.

**Comment by ksmith0** [comment]
This is very similar to the hist scanner.

**Comment by spaulaus** [comment]
It's also identical to a program that @cthornsb wrote yesterday apparently. We need to have people actually start to document these kinds of things so that I (and others) don't waste hours of work reproducing things that already exist. 

Also, i have no idea what the "host scanner" is.

**Comment by ksmith0** [comment]
It is hist scanner. I think it is on the histPlotter branch.

**Comment by spaulaus** [comment]
The idea here isn't to have any immediate display of the data, just a straight and quick conversion. The users would then just load the root file and plot from the tree.

**Comment by spaulaus** [comment]
But as I said I have no idea what @cthornsb actually wrote since it's not documented anywhere.

**Comment by ksmith0** [comment]
That is what the hist plotter does. It also allows for immediate display, but without any definition of plots it just makes the root file.

**Comment by spaulaus** [comment]
Gotcha.

**Comment by ksmith0** [comment]
It is abbot of a mess, because the underlying scanner and unpacker classes were changing while it was being developed. It is also not documented as it's a work in progress.

**Comment by spaulaus** [comment]
I would like to start having new work documented similar to #232 . All this undocumented work leads to waste.

**Comment by spaulaus** [comment]
I've modified the name of this issue along with the description to take into account the discussion with @ksmith0.

**Comment by spaulaus** [comment]
@ksmith0 I've rebased the `rootScanner` branch onto dev and forced pushed. Just be aware if you come back to it in the future.

**Comment by spaulaus** [comment]
@ksmith0 I'm looking at the rootScanner code and it seems like you're doing a lot more than just decoding the header and stuffing it into a ROOT tree. For example on [this](https://github.com/pixie16/paass/blob/rootScanner/Analysis/Utilities/RootScanner/source/HistScannerChanData.cpp#L42) line you're finding the baseline of the traces and setting the information. 

Where do you want this program to do. This is much more complicated than what I envisioned. To simplify the process I had thought just to decoded the 4 word header and stuff it into a tree. 

Can you explain more about what you'd like to accomplish with this? Maybe we can break it into two separate programs?

**Comment by ksmith0** [comment]
This program never had clearly defined goals and as such as been changed on a whim to suite my needs. In general I would describe the goal as a rather simple scan code that was designed to function with an online plotting capability as well as providing some ROOT output. I feel that in addition to the unpacking of the four word header, some additional simple analysis of the waveform could be provided (traceQdc, timing, etc..). 

I would be reluctant to separate the programs. Perhaps some simple switches to turn off the gui and run only in batch mode would help to accomplish your goals.

Finally, this type of scan code is very well suited for the work at other facilities and I would like to see its development continued.
