### ISSUE TITLE
Code does not parse <TrapFilters> node of the xml

### ISSUE THREAD

**Issue by tking53** [pixie16/paass#249]
# Description
`GlobalsXmlParser.cpp` is where this is (trys to be) parsed.
Part of the issue I think I have fixed, but the second part is unknown to me. The first part of the issue was the missing `.empty()` in the leading `if` condition; without it the loop is never entered. The second part is that the values are never parsed. This is from kqxhc, and I'm on my Ornl2016 Branch but I'm even with dev. I rebased yesterday after the `Rootfitter` pull request  (#239). 

The parsing code for pixie16/dev is [here](https://github.com/pixie16/paass/blob/1f5c39ead06011a9275887ba87696f3869817c7f/Analysis/Utkscan/core/source/GlobalsXmlParser.cpp#L307-L326). This has been updated in my fork, which is [here](https://github.com/tking53/paass/blob/bba6c8f2a13679bc55b3b2e2baa85b0aa97e53fb/Analysis/Utkscan/core/source/GlobalsXmlParser.cpp#L322-L351
).

The `cout` for the name is empty, and the attribute values are 0 (or the defaults when the codes running)

# Work to be done
1. The Trapezoidal filter parameters are parsed properly. 

# Acceptance Criteria
1. All of the software compiles
1. The TraceFilterAnalyzer returns the proper values parsed from the node.

**Comment by spaulaus** [comment]
Please make sure your bug reports conform to the proper style. Do not copy/paste the code from some unknown location and commit. You can link directly to a line from a specific commit. That output should be summarized and the extraneous information removed.

**Comment by tking53** [comment]
updated

**Comment by spaulaus** [comment]
See Issue #199 or #243 for proper formatting. You also didn't remove the extraneous information from the original post.
