### ISSUE TITLE
Need to have variable TraceDelay

### ISSUE THREAD

**Issue by spaulaus** [pixie16/paass#251]
# Description
I have identified two data sets (ISOLDE 2015 and ORNL 2016) that have trace delays that vary depending on the detector type that was used. The analysis software only supports a single trace delay. I have also been asked by users if this is something that we could support. Clearly there is a need. 

# Proposed solution(s)?
# Option 1
Set the trace delay via a similar interface to the WaveformRange or Fitting parameters. However, this would only provide control on a per detector type:subtype basis. At this level there's no guarantee that the type:subtype combination will all have the same delay (after all we assumed all types:subtypes had the same delay prior to this). This solution is pretty quick to implement since it just means we need to add a bit of code to the GlobalsXmlParser and the Globals class. 

# Option 2 
Create this as a channel parameter like a calibration. This will  ensure that we can set this parameter for each module/channel combination. This solution will take significantly more time to implement since we'll need a number of new classes to handle the new features. This also means that we should concatenate the WalkCorrector and Calibrator into a more comprehensive class (ChannelSettings?) **I think that this solution makes the most sense in the long term.**

**Comment by tking53** [comment]
I think if we could quickly put Option 1 into effect, that would allow Option 2 to have the development time it needs to not be rushed. 
We could also during the implementation of Option 2 reimplement Option 1 as a "coarse" option. So we would have 3 ways to deal with this, Global (the way it is now), Coarse (Type:Subtype), and Fine (Channelwise). I also agree that Option 2 makes the most sense but it makes the Config File really long. (1 or 2 new lines per channel with traces; Im thinking of Dome-Vandle or NEXT ). So having ways to handle this on a coarser level than Channelwise, I think would be very useful.
Hopefully this is a niche feature, and we can continue as we always have. While having this as a backup if we do this by accident again.

**Comment by spaulaus** [comment]
Well it's happened twice during experiments and a user has requested it. I don't think it's niche. What's most troubling is the experiment parts. What else have we gotten wrong?

**Comment by tking53** [comment]
I have a xml type:subtype style fix for this. i will submit a PR after the holiday (and a bit more testing).

**Comment by spaulaus** [comment]
Resolved this issue, see Pull Request #269
