### ISSUE TITLE
PAASS_BUILD_SCAN_UTILITIES does not do anything

### ISSUE THREAD

**Issue by tking53** [pixie16/paass#252]
# Description 
The scan utilities (Scope, headreader, set2ascii and set2root) are still built even if this flag is off. I think this is just a missing if statement in the root CMakeLists.txt

# **Work To Be Done**
Fix the appropriate CMakeLists.txt 

# **Acceptance Criteria**
Code compiles what we expect it to based on the cmake flags
Flag does what it is supposed to do, which is toggle the building of the Utility programs on/off

**Comment by spaulaus** [comment]
The flag is intended to control the compilation of these utility programs. We should update `Analysis/CMakeLists.txt` to actually use the flag properly.
