### ISSUE TITLE
eventWidth is not applied to UtkUnpacker

### ISSUE THREAD

**Issue by rin-yokoyama** [pixie16/paass#253]
# Description
eventWidth of [UtkUnpacker](https://github.com/pixie16/paass/blob/dev/Analysis/Utkscan/core/source/UtkUnpacker.cpp) is not loaded properly. It is initialized with the default value of [Unpacker](https://github.com/pixie16/paass/blob/dev/Analysis/ScanLibraries/source/Unpacker.cpp#L220) and uses this value regardless of the input config file.

# Work to be done
Set proper eventWidth value of UtkUnpacker from [Globals](https://github.com/pixie16/paass/blob/dev/Analysis/Utkscan/core/source/Globals.cpp).

# Acceptance Criteria
1. All of software compiles
2. Builds events with a proper time window given in the input config xml.

**Comment by rin-yokoyama** [comment]
I send a pull request to this issue

**Comment by ksmith0** [comment]
You can simply list the issue number with the pound symbol in the pull request (#254) to cross document.

**Comment by tking53** [comment]
This was addressed in pull requests #254 and #257 . Closing the issue.
