### ISSUE TITLE
utkscanor will not compile with CMake 3.6.1

### ISSUE THREAD

**Issue by ksmith0** [pixie16/paass#255]
utkscanor fails to compile with gcc version 4.8.2 20140120 (Red Hat 4.8.2-15) and cmake version 3.6.1. It looks as if the library paths are stripped down. Even adding the correct search path does not resolve the issue. This is caused by ORPHAS libraries as they do not follow the standard naming scheme with the prefix 'lib'. 

Compiling with the same gcc and cmake 2.8.12.2 does not show this behavior.

```
/opt/rh/devtoolset-2/root/usr/libexec/gcc/x86_64-redhat-linux/4.8.2/ld: cannot find -lscanorlib
/opt/rh/devtoolset-2/root/usr/libexec/gcc/x86_64-redhat-linux/4.8.2/ld: cannot find -lorphlib
/opt/rh/devtoolset-2/root/usr/libexec/gcc/x86_64-redhat-linux/4.8.2/ld: cannot find -lacqlib
/opt/rh/devtoolset-2/root/usr/libexec/gcc/x86_64-redhat-linux/4.8.2/ld: cannot find -lipclib
collect2: error: ld returned 1 exit status
make[2]: *** [Analysis/Utilities/Scope/source/scope] Error 1
make[2]: Leaving directory `/root/programs/paass/build'
make[1]: *** [Analysis/Utilities/Scope/source/CMakeFiles/scope.dir/all] Error 2
make[1]: Leaving directory `/root/programs/paass/build'
make: *** [all] Error 2
```

**Comment by ksmith0** [comment]
This can be avoided by manually copying the compile statement and correcting the paths. The compile command can be captured with the following command:

```
VERBOSE=1 make
```

**Comment by spaulaus** [comment]
Cmake 3.7.1 and gcc (Ubuntu 5.4.0-6ubuntu1~16.04.4) 5.4.0 20160609 no longer have this issue.

**Comment by ksmith0** [comment]
This again is a bill only issue. I believe it did not work with CMake 2 either.

**Comment by spaulaus** [comment]
> This again is a bill only issue.

Do we need to bother patching it then?

**Comment by spaulaus** [comment]
Since this is specific to a single computer, I'm going to close this as "won't fix".

**Comment by tking53** [comment]
I hope this is specific to an installation with that computer (i.e. maybe human error during the install somewhere) . When we get some time were we don't need this laptop, someone will reinstall the os, ORPHAS, and paass. If it comes back after the reinstall, or shows up on one of the other computers; we may need to investigate it more.
