### ISSUE TITLE
C++11 Support

### ISSUE THREAD

**Issue by ksmith0** [pixie16/paass#26]
The C++11 support in the main CMake file seems to have a bug. The following code doesn't make sense. On a machine with C++ v 4.8 the C++11 flag was not enabled and the code failed to compile.

```
if (CMAKE_COMPILER_IS_GNUCXX)
    if (${CMAKE_CXX_COMPILER_VERSION} VERSION_GREATER "4.3")
        if(${CMAKE_CXX_COMPILER_VERSION} VERSION_LESS "4.7")
            set(CMAKE_CXX_FLAGS "${CMAKE_CXX_FLAGS} -std=c++0x")
        endif(${CMAKE_CXX_COMPILER_VERSION} VERSION_LESS "4.7")
    else(${CMAKE_CXX_COMPILER_VERSION} VERSION_GREATER "4.6")
        set(CMAKE_CXX_FLAGS "${CMAKE_CXX_FLAGS} -std=c++11")
    endif(${CMAKE_CXX_COMPILER_VERSION} VERSION_GREATER "4.3")
```

**Comment by ksmith0** [comment]
This is in the dev branch starting commit d2c295d35138

**Comment by ksmith0** [comment]
The current statement can never reach the line with `-std=c++11` and the first if block only sets the flag for versions >4.3 and <4.7

**Comment by spaulaus** [comment]
That's strange because on my laptop it compiles with -stc=c++11. I have gcc v 6.1.1. I will look into this.

**Comment by ksmith0** [comment]
I don't like the way GitHub closes these. Feels like your hanging in the wind and I've got to dig into the commit to find out what happened.

Thanks for fixing this.

**Comment by spaulaus** [comment]
Haha, actually, that's how _I_ closed it, the hook didn't work for some reason.
