### ISSUE TITLE
Update line length from 80 to 130 characters

### ISSUE THREAD

**Issue by spaulaus** [pixie16/paass#268]
I've had some discussions with my development team and they all advocate 130 character line limits. I was thinking that this might be good for this project since there are a number of lines that we've had to format in funny ways. 

Are there any thoughts on this?

**Comment by ksmith0** [comment]
More than 80 and it won't fit on a punch card anymore :-(

**Comment by spaulaus** [comment]
> More than 80 and it won't fit on a punch card anymore :-(

I see that LANL has upped their security game.

**Comment by spaulaus** [comment]
@ksmith0 : I would like to reach a consensus on this. What's your vote?

**Comment by ksmith0** [comment]
A consensus between you and me?

Well I used to just let the lines go as long as needed and that worked well for me. I see the advantage of finding a good place to break a line for readability and on modern computer 130 is not so long (although 120 is 50% more than 80 and that makes me happy for some reason). I vote for longner lines. It's silly to stick to a format from 1928 for a technology that has been obsolete for decades.

**Comment by spaulaus** [comment]
Not just a consensus between us but among the development group. Vote on my original post.

**Comment by ksmith0** [comment]
> Vote on my original post.

What does that mean?

**Comment by spaulaus** [comment]
> What does that mean?

I meant we can add reactions to the original post to act as a voting system.

**Comment by ksmith0** [comment]
Ahh, the mobile version doesn't show the reactions.

![img_0398](https://cloud.githubusercontent.com/assets/7395803/26276377/b8e8d034-3d33-11e7-9249-0e7a1a9f0c23.PNG)
