### ISSUE TITLE
Split ScanLibs from UTK Scan

### ISSUE THREAD

**Issue by ksmith0** [pixie16/paass#27]
Commit b4e3563 highlighted an issue in which SCAN_LIBS and SCAN live in the same folder. These should be separated to clean up the cmake code and reduce possibility of dependency issues.

Also, cmake should check the value of USE_SCAN and USE_SCAN_LIBS and warn the user if they have selected SCAN without LIBS.

**Comment by spaulaus** [comment]
I'm unsure what you are referring to as dependency issues. All scan software completely depends on the lib files (Unpacker, ScanInterface and XiaData). This actually raises a bigger questions as to what exactly should be included in the PixieScan library. Messenger and the Notebook are useful for other scan implementations. 

However, you are correct in that the build options were not implemented appropriately, which I will fix.

**Comment by ksmith0** [comment]
I mean that those who want the PixieScan library (Cory, perhaps Steve P in the future) do not want to have that code tangled with the rest of UTK scan. I think we should move the scan libs up to another folder or UTK scan down a layer.

**Comment by spaulaus** [comment]
I do not necessarily agree with the placement, since they are "core" components of any scan software. The build flags are currently being altered to enable the requested functionality.

**Comment by ksmith0** [comment]
Sorry I misunderstood the structure. It looks as though it is already built the way I was intending although it could be clarified by moving scan/source and scan/include in scan/scanlib/. 

After that resolution, the scope of this issue is now purely the USE flags issue.

**Comment by spaulaus** [comment]
Resolved with 309d76b6c863fe0952e59c9378d3ba7f8fa39915

**Comment by ksmith0** [comment]
I thought this had been resolved? I'm confused now as all the comments made here seem to be gone and the Scan/utkscan folder is gone?

**Comment by ksmith0** [comment]
Started working on this in the scan_refactor branch. Compiled everything except for UTK_SCAN due to issue #31. I will post a merge request once I'm confident it works for all projects.

@cthornsb Can you check that the scan_refactor branch is still working for you?

**Comment by spaulaus** [comment]
As mentioned in issue #33 I think something got garbled in a merge when trying to import the changes that @cthornsb made in the main PixieSuite2 repository.

**Comment by ksmith0** [comment]
This negates the usefulness of the scan_refactor branch. I assume we could kill it unless we want to compare the two approaches.

**Comment by spaulaus** [comment]
The implementations are virtually identical with the exception of the Skeleton and Scope (which need refactored anyway with respect to issue #29). I move to delete the branch.

**Comment by ksmith0** [comment]
Looks like it has been deleted.
