### ISSUE TITLE
Recording data, but no file open!

### ISSUE THREAD

**Issue by cthornsb** [pixie16/paass#39]
A certain sequence of commands in poll2 will produce the error message "[ERROR] Recording data, but no file open! Opening a new file." The sequence is as follows:

```
run
stopacq
clo
startacq
```

![screenshot from 2016-08-15 16-44-48](https://cloud.githubusercontent.com/assets/7407864/17679169/3ecf7376-6308-11e6-9d23-cecad7ba02cb.png)

**Comment by cthornsb** [comment]
Resolved in commit 506acff.

**Comment by ksmith0** [comment]
This is a duplicate of pixie16/PixieSuite2#63
