### ISSUE TITLE
Invalid channel specification (-1)

### ISSUE THREAD

**Issue by cthornsb** [pixie16/paass#40]
IsNumeric, the function poll2 uses to ensure the validity of numeric input, returns false for negative numbers. This is due to the '-' character not being recognized by this function. Introduced in commit 98cc45f.

![screenshot from 2016-08-15 17-03-47](https://cloud.githubusercontent.com/assets/7407864/17679640/43667914-630a-11e6-9a31-86c1d5d45a0f.png)

**Comment by cthornsb** [comment]
Resolved in commit 560fff7.

**Comment by ksmith0** [comment]
Commit 98cc45f also resolved issue pixie16/PixieSuite2#87.
