### ISSUE TITLE
No longer have the ability to append data to a file

### ISSUE THREAD

**Issue by cthornsb** [pixie16/paass#46]
Commit 506acff effectively this removed the ability to append data to a data file. @spaulaus and @ksmith0, what do you think of this change? Do you think we should preserve the ability to do this?

**Comment by ksmith0** [comment]
I think we should remove the ability. I believe it is dangerous to stop and acquisition as the setup may change during that time. For example pwrite becomes available again.

**Comment by cthornsb** [comment]
I agree, I just wanted to check and see what everyone else thought. I don't really see the reason you would want to append to a file instead of just opening a new one. It's not like a new header takes up a lot of room or anything.

**Comment by spaulaus** [comment]
I concur with the above comments. I can think of more times that this hurt rather than helped when using pacman.

**Comment by ksmith0** [comment]
We all agree that the removal of this ability is the preferred operating principal, therefore no action is necessary.

**Comment by ksmith0** [comment]
We have removed the slo(se) command as it is no longer necessary in commit ee8c03f4bb21160699c8625d7c98aed4367e7ef4.
