### ISSUE TITLE
Wiki page: Directory Structure Out dated

### ISSUE THREAD

**Issue by ksmith0** [pixie16/paass#47]
The page about [Directory Structure ](https://github.com/pixie16/paass/wiki/Directory-Structure)on the wiki is out dated. Looks like it reflects an older pixie_scan structure.

**Comment by ksmith0** [comment]
@spaulaus Interested in a little wiki edit? Especially now that the whole structure has been changed again.

**Comment by spaulaus** [comment]
Sure. I'm sick of looking at this configuration anyway.

**Comment by spaulaus** [comment]
Resolved. I updated the directory structure to match dev.
