### ISSUE TITLE
Tab complete on multi-command string

### ISSUE THREAD

**Issue by cthornsb** [pixie16/paass#48]
If more than one command (separated by a semi-colon) is being typed by the user, moving the cursor to a command before a semi-colon and attempting to tab-complete a previously written command garbles the input string. e.g.

![screenshot from 2016-08-16 17-25-15](https://cloud.githubusercontent.com/assets/7407864/17716372/6ee54e22-63d6-11e6-9d9a-03a024030e24.png)

Bug introduced in commit 7b90e21.

**Comment by ksmith0** [comment]
We just need to do a left from the current cursor position to the previous space or semi-colon.

``` c++
size_t delimPos = find_last_of(" ;",cursorPos);
std::string autoComplete = substr(delimPos, cursorPos - delimPos);
```

Needs some checks etc.

**Comment by ksmith0** [comment]
Fixed upstream. Closing this issue.
