### ISSUE TITLE
pwrite/pmwrite should display original values before changing them

### ISSUE THREAD

**Issue by cthornsb** [pixie16/paass#49]
Whenever the user calls pwrite, pmwrite, or toggle, poll2 should display the original value before changing it. This will make it possible to easily change a parameter back to its original value if needed.

**Comment by cthornsb** [comment]
Added this feature in commit 9bd3639.

![screenshot from 2016-08-16 17-57-19](https://cloud.githubusercontent.com/assets/7407864/17717390/ba0c558a-63db-11e6-8d4d-881ef5d0afbd.png)

**Comment by ksmith0** [comment]
Duplicate of pixie16/PixieSuite2#98
