### ISSUE TITLE
Poll2 continues to run after disk is full

### ISSUE THREAD

**Issue by cthornsb** [pixie16/paass#50]
Poll2 continues to run after the disk fills up. It displays an error message but continues to run the acquisition with an [ERROR] flag in the status bar. If data cannot be written to disk, then the acquisition probably doesn't need to be running. This is an issue on un-monitored overnight runs for example.

**Comment by ksmith0** [comment]
This is an extension of pixie16/PixieSuite2#47 (Log file stops working if disk is full)

**Comment by ksmith0** [comment]
This issue was resolved in b17d0f0
