### ISSUE TITLE
Typing a semi-colon in a title

### ISSUE THREAD

**Issue by cthornsb** [pixie16/paass#51]
As of commit 7b90e21, it is now impossible to type a semi-colon in a data file title. The terminal sets everything up to the semi-colon as the title and then tries to execute everything after.

**Comment by ksmith0** [comment]
Eh is that important?

**Comment by cthornsb** [comment]
It turns out that I type a lot of them in my titles. That's the only reason I even noticed it. It could be important if you weren't paying attention and didn't notice what was happening.

**Comment by ksmith0** [comment]
We could require double quotes around the title.

**Comment by ksmith0** [comment]
We have decided that title will require double quotes.

**Comment by ksmith0** [comment]
Resolved upstream.
