### ISSUE TITLE
TraceAnalyzer class needs to be cleaned up

### ISSUE THREAD

**Issue by spaulaus** [pixie16/paass#6]
The TraceAnalyzer class and its children are still a little bit of a mess, some work needs to be done to clean these up. This also extends to the Trace class, which has gotten much too complicated for its own good.

**Comment by ksmith0** [comment]
@spaulaus Was this worked on in the Decoding Update #156?

**Comment by spaulaus** [comment]
No

**Comment by spaulaus** [comment]
I'm going to close this as part of it was already handled, the rest isn't specific enough to execute against.
