### ISSUE TITLE
HisDrr produced files are not always readable by DAMM

### ISSUE THREAD

**Issue by ksmith0** [pixie16/paass#64]
@spaulaus reported this issue.

**Comment by ksmith0** [comment]
Are these the HisDrr files from MCA or ScanLib?

**Comment by spaulaus** [comment]
ScanLib is the only time we've really seen this issue. We haven't undergone thorough testing to figure out what's causing this issue.

**Comment by spaulaus** [comment]
I again think that this isn't a huge issue. The files are always readable by versions of DAMM that are compiled on the computer.
