### ISSUE TITLE
Modify set2ascii to provide correct tau values.

### ISSUE THREAD

**Issue by ksmith0** [pixie16/paass#72]
The TAU value is stored in the set file as an IEEE standard. We are incorrectly treating it in set2ascii.

> Hi Mitch,
> 
> Stan is correct and you also figured it out already: the preamp tau has the IEEE standard format. The reason for that is we need to store it in the format which allows decimal fractions, e.g. 46.25 us. The only other number that has the same IEEE format is the baseline values in the list mode data, since the baseline can have decimal factions too.
> 
> Regards,
> Hui

**Comment by spaulaus** [comment]
This also occurs in the data decoding of the Baseline value.
