### ISSUE TITLE
FindWaveform bounds computed incorrectly

### ISSUE THREAD

**Issue by ksmith0** [pixie16/paass#78]
@wapmanzoo has seg faults in utkscan from WaveformAnalyzer::FindWaveform. After a gdb session we identified the issue on line 124 of [WaveformAnalyzer.cpp](https://github.com/pixie16/paass/blob/dev/Scan/utkscan/source/analyzers/WaveformAnalyzer.cpp):

``` c++
Trace::iterator tmp = max_element(low, high);
```

The value `low` was 254 while `high` was 154. I believe `max_element` requires low < high. The config file was set to have trace length of 200 ns and the trace length was set to 144 ns.

**Comment by spaulaus** [comment]
I am unsure how the low could have been greater than the high. The low is set to be 

```
    Trace::iterator low = trc_->begin() + 15 + lo;
```

The high is set to be no greater than the size of the trace. In fact, the TraceLength parameter has not been checked or used for years.

**Comment by spaulaus** [comment]
I have attempted to address this problem in commit df4c741db59a7a32cc2c85d8d89aea6751ad876c. @wapmanzoo, please let me know if this closes this issue.

**Comment by ksmith0** [comment]
`lo` = 6
`hi` = 13
`trc_->begin()` = 158
`g_->traceDelay()` = 1.2944174324888161e-312
`g_->adcClockInSeconds()` = 4e-9
`high` = 158
`trc_->end()` = 421
`low` = 159
segfault on max_element(low, high)

**Comment by ksmith0** [comment]
The new commit does not segfault, but it does not exit cleanly and corrupts the terminal on CTKS_Trial_003.ldf

We also tried run_034.ldf and got the following message: (no corrupted terminal)

```
! The high bound for the waveform search was lower than the low bound. This should never have happened and I have no idea why it did. 
```

**Comment by spaulaus** [comment]
Interesting that it has different behavior for different lfds. I have the feeling that this issue is due to a misconfigured XML file. I do not get the message with the xml file that I am using locally. I have been using run_034.ldf for the tests. You can view the XML at [this](https://gist.github.com/spaulaus/e2eed4aa0d28a7ab6c965855ba74a443) link.

**Comment by spaulaus** [comment]
This error turns out to be due to a misconfigured XML file. The TraceDelay was not defined and the WaveformAnalyzer did not assume some kind of reasonable default. I will leave this issue open until I implement a default value (likely 1/2 the trace length).
