### ISSUE TITLE
Move share/scan to Scan/utkscan/share

### ISSUE THREAD

**Issue by ksmith0** [pixie16/paass#79]
The items associated with each subpackage should live within those folders. This allows a simpler control of and extraction of subpackages.

**Comment by spaulaus** [comment]
No complaint from me.

**Comment by spaulaus** [comment]
This has been addressed and I have put in a merge request.

**Comment by ksmith0** [comment]
Resolved in commit 881c4ad8404672e3a7e1201b444806300150b1d8
