### ISSUE TITLE
ReadBuffer incorrectly decodes data

### ISSUE THREAD

**Issue by spaulaus** [pixie16/paass#8]
The Unpacker::ReadBuffer incorrectly decodes the data from the XIA modules. It currently only works for a specific version of Revision F, and needs to be updated and fixed so that it can handle the previous revisions, as well as the newest revision of F.

**Comment by spaulaus** [comment]
I have confirmed that the software cannot properly decode data written with the firmware provided by XIA on 06/06/2012. This will include most of the VANDLE related files.

**Comment by ksmith0** [comment]
A large portion of this work was resolved in #156 and is further being improved in #180
