### ISSUE TITLE
The Tests for the software do not install

### ISSUE THREAD

**Issue by spaulaus** [pixie16/paass#83]
The tests for the software should be installed in some central location. Maybe `${CMAKE_INSTALL_PREFIX}/bin/tests`?

**Comment by ksmith0** [comment]
Then we have to add the tests folder to the path as well?

**Comment by spaulaus** [comment]
I don't think we have to add them to the path. It's just so that if users want to run the tests they have them located in a reasonable place. 

Maybe instead we have it as `${CMAKE_INSTALL_PREFIX}/tests`?

**Comment by ksmith0** [comment]
I'm back and forth on `bin/tests` or `tests`. I don't think it will matter much, but it may be nice to be able to ask a user to run a test and if they aren't in the path that is harder. It's not that hard though. I'm voting for just `tests`.

**Comment by ksmith0** [comment]
Be sure to change the install location for the terminal test program in Core as well.

**Comment by spaulaus** [comment]
I have no problem with `tests`. Unless @cthornsb has a major issue with it then, we'll go with that.

**Comment by ksmith0** [comment]
While we are discussing it I see we have two cmake flags for building tests `BUILD_TESTS` and `BUILD_UTKSCAN_TESTS` Can we just reduce down to one?

**Comment by ksmith0** [comment]
What is the status of this? I know we have made some effort to change the way we handle unit tests. @spaulaus can you comment?

**Comment by spaulaus** [comment]
Haha, I think it's gotten worse. We now have BUILD_TESTS and BUILD_UNITTESTS. I don't think that BUILD_UTKSCAN_TESTS is there anymore?

This also has a bug I found today where you can enable the tests without enabling GSL and it will try to build the test. This will need addressed. 

**The short: I think we need at least 2 test flags: BUILD_ TESTS and BUILD_UNITTESTS.**

**Comment by spaulaus** [comment]
The unittests are installed to bin/unittests. I think this pretty much resolves our issue here.
