### ISSUE TITLE
Failed to get histogram data from module 1

### ISSUE THREAD

**Issue by wapmanzoo** [pixie16/paass#84]
Poll2 gave the following error message scrolling repeatedly:

```
Failed to get histogram data from module 1
```

Pixie16msg.txt tail reads:

```
*ERROR* (Pixie_Main_Memory_IO) - Failed to open PLX DMA channel in module 1, rc =534 [timestamp]
*ERROR* (Pixie16ReadHistogramFromModule): failed to get histogram data from module 1, retval=-1 [timestamp]
```

This has occurred for each module at different times but only one module per run. If I quit poll2 before trying to write to the DSP it will save the current.set file from being erased. This seems to happen now, every time, within a minute of running MCA, paramScan, scope, but seems to not occur when recording an ldf.  The MCA, paramscan runs seem to continue through these errors and data increases and a root file is made.
I suspect a process that might not be used during normal recording that is called to help fill the MCA and scope and such.

**Comment by ksmith0** [comment]
We should note that this issue is on nitemp. 

You had mentioned that you rebooted the computer some time ago. Did you reboot cleanly or perhaps did you power cycle it while it was still running?

**Comment by wapmanzoo** [comment]
I washed my hands before rebooting yes. I have used the ubuntu OS to restart the computer. Then start poll2 with no flags.

**Comment by ksmith0** [comment]
Ubuntu OS? 

I have a feeling that your xia software has been corrupted in the same way that your set file has. I'd like to reinstall it.

**Comment by wapmanzoo** [comment]
I meant Centos OS on nitemp.

**Comment by ksmith0** [comment]
Is it always the same module that crashes?

**Comment by wapmanzoo** [comment]
I've seen module 1, 5, and 3 do this, at least, but I think just one at a time.

**Comment by wapmanzoo** [comment]
I also get the following error message right after loading the file in pixie_ldf_c

```
>file name.ldf 
>go
 failed to get histogram from module 4
Intializing scan .......................................
*First buffer at ...
```

(Be aware "failed to get histogram from module 4" is the title and run number.)
The rest seems to go along as normal; loading and constructing etc.
The histogram seems to only have a few events in it. I also saw an error

reading record# 114 from unit# 31

then the number of buffers processed was only 109 and it was done.
It did not crash. I typed >end to finish and look at the histogram it made.

**Comment by spaulaus** [comment]
Do you have the histogram feature enabled in the CSRA? I've never seen this error before in any version of  scan since we're not directly decoding histograms from modules.

**Comment by wapmanzoo** [comment]
The channel csra are: good channel + traces+ pairwise for VANDLE and MCPs. (8452?) For the Si it was good and polarity. Is there a module setting for this histogram feature? Also the error occurs for modules even if there are no triggered events in that module.

-Bill

William A. Peters Ph.D.
ORNL
Univ. of Tenn. 
865 576-6798

**Comment by wapmanzoo** [comment]
The first error message in Pixie16msg.txt, before the repeated list from the my primary posting above, is:

```
*ERROR* (Pixie_Main_Memory_IO) - PlxPci_DmaTransferUserBuffer failed while reading from external memory in module 5 , rc=513 [datestamp]
```

**Comment by ksmith0** [comment]
I am starting to believe this is something we need to contact XIA about.

**Comment by spaulaus** [comment]
This has been escalated to XIA. We received a response from Hui : 

> Hi Karl,
> 
> To check the return codes from the plx library, please see the file PlxStat.h in the inc folder of the Pixie-16 Clib. I also attached a copy.
> 
> In the PlxStat.h file, you could see the PLX_STATUS, in which the first element is ApiSuccess with a value of 512 (0x200). Subsequent element will have values of 513, 514, ...
> 
> So the first line of your ERROR messages has the rc = 513, which means "ApiFailed", and the second line rc = 534, which means "ApiDmaChannelUnavailable".
> 
> It appears these errors are related to the PLX API function calls, and I am wondering whether this has something to do with the OS that is running for your data acquisition software. Or could it be related to a 32-bit or 64-bit architecture? Memory allocation problem? Could you try a different computer?
> 
> I am interested in seeing how you would solve this problem.
> ​Best regards,
> Hui

It seems we will still have to do some digging on our part. Though, from the response, I feel this may be a computer specific problem.

**Comment by ksmith0** [comment]
I have marked it has wontfix, until this becomes a more severe issue.
