### ISSUE TITLE
UDP Packet investigation

### ISSUE THREAD

**Issue by spaulaus** [pixie16/paass#9]
Investigate and add pause between sending UDP packets for poll.

**Comment by ksmith0** [comment]
Which UDP packets are we talking about here?

**Comment by spaulaus** [comment]
This was probably the worse issue report ever, but came out of one of our brainstorming sessions. I suspect that we are talking about some kind of SHM feature?

**Comment by ksmith0** [comment]
Closing it as we have no idea what it is.
