### ISSUE TITLE
ScanLib multiple input files from terminal.

### ISSUE THREAD

**Issue by ksmith0** [pixie16/paass#95]
@wapmanzoo requested that it be possible to scan multiple input files together in the ScanInterface. This seems useful and should be implemented.

**Comment by spaulaus** [comment]
What about implementation of a command file similar to poll2? That should be relatively easy to use.

**Comment by ksmith0** [comment]
That functionality is built into the terminal itself so every program has that capability. The request was to list multiple files at the bash prompt, but perhaps @wapmanzoo is happy with this possibility. We could pass an argument from bash to tell the scan to auto executive a command file.

**Comment by wapmanzoo** [comment]
Sounds good. Since im using pixie scan right now I am using the cmd feature to scan a batch of ldfs into one his file. 

-Bill

William A. Peters Ph.D.
ORNL
Univ. of Tenn. 
865 576-6798

**Comment by ksmith0** [comment]
I'm closing this as the agreed upon solution already is implemented.
