### ISSUE TITLE
UtkScan does not create the 3200 histograms

### ISSUE THREAD

**Issue by ksmith0** [pixie16/paass#96]
@wapmanzoo reported that the utkscan with this [Config.xml](https://github.com/pixie16/paass/files/482696/Config.txt) does not produce the 3200 histograms.

**Comment by wapmanzoo** [comment]
This issue is due to an incorrectly configured config file. The following section has a mistake in the VandleProcessor:

``` xml
<DetectorDriver>
    <Processor name="BetaScintProcessor" />
    <Processor name="VandleProcessor" bars="small" NumStarts="2" res="2" offset="200" />
    <Analyzer name="WaveformAnalyzer"/>
    <Analyzer name="FittingAnalyzer" type="gsl" />
</DetectorDriver>
```

The VandleProcessor should not have the tag `bars="small"`, but instead should be `types="small"` as below:

``` xml
    <Processor name="VandleProcessor" types="small" NumStarts="2" res="2" offset="200" />
```
